Repository codestates-seb/seb40_main_014, pull requests merged in 2022-12, with the labels that each got.

#152 ✨Feat: 방 내에서 유저페이지, 팔로우 기능 구현 / 어드민일 경우 방 삭제 안하기 기능 구현
  client/src/components/home/Footer.tsx
  client/src/components/home/Header.tsx
  client/src/components/room/PeopleList.tsx
  client/src/components/room/RoomCreateForm.tsx
  client/src/components/room/RoomUpdateForm.tsx
  client/src/pages/Room.tsx
  client/src/routes/AppRouter.tsx
Labels: front-end, feature

#177 Fix/ranking
  server/server/src/main/java/com/mainproject/server/member/entity/Member.java
  server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
  server/server/src/main/java/com/mainproject/server/member/repository/MemberRepository.java
  server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
  server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java
  server/server/src/main/resources/application.properties
Labels: back-end

#179 🔥 remove : guest
  server/server/src/main/java/com/mainproject/server/auth/config/SecurityConfig.java
  server/server/src/main/java/com/mainproject/server/auth/config/WebConfig.java
  server/server/src/main/java/com/mainproject/server/auth/filter/JwtAuthenticationFilter.java
  server/server/src/main/java/com/mainproject/server/auth/handler/GuestFailureHandler.java
  server/server/src/main/java/com/mainproject/server/auth/handler/GuestSuccessHandler.java
  server/server/src/main/java/com/mainproject/server/auth/handler/OAuth2SuccessHandler.java
  server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
  server/server/src/main/java/com/mainproject/server/member/entity/Member.java
  server/server/src/main/java/com/mainproject/server/member/service/MemberDetailsService.java
  server/server/src/main/java/com/mainproject/server/member/service/MemberService.java
  server/server/src/main/resources/application.properties
Labels: back-end

#180 🔥 remove : category관련 불필요한 파일삭제 및 수정
  server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/LikePlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/Category.java
  server/server/src/main/java/com/mainproject/server/playlist/repository/CategoryRepository.java
Labels: back-end, chore

#184 ✨ feat : RankingScheduler
  server/server/src/main/java/com/mainproject/server/ServerApplication.java
  server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
  server/server/src/main/java/com/mainproject/server/member/entity/Member.java
  server/server/src/main/java/com/mainproject/server/member/entity/RankingList.java
  server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
  server/server/src/main/java/com/mainproject/server/member/repository/MemberRepository.java
  server/server/src/main/java/com/mainproject/server/member/repository/RankingListRepository.java
  server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
  server/server/src/main/java/com/mainproject/server/member/service/RankingScheduler.java
  server/server/src/main/java/com/mainproject/server/response/ErrorResponse.java
Labels: back-end, feature

#185 🔨 chore : RankingTime
  server/server/src/main/java/com/mainproject/server/member/dto/RankResponseDto.java
  server/server/src/main/java/com/mainproject/server/member/entity/RankingList.java
  server/server/src/main/java/com/mainproject/server/member/service/RankingScheduler.java
Labels: back-end

#196 🐛 fix : ranking
  server/server/src/main/java/com/mainproject/server/chatroom/mapper/ChatRoomMapper.java
  server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
  server/server/src/main/java/com/mainproject/server/member/service/RankingScheduler.java
  server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
  server/server/src/main/resources/application.properties
Labels: back-end

#203 🐛 fix : TopDj
  server/server/src/main/java/com/mainproject/server/chatroom/mapper/ChatRoomMapper.java
  server/server/src/main/java/com/mainproject/server/member/repository/MemberRepository.java
  server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
  server/server/src/main/java/com/mainproject/server/member/service/MemberService.java
  server/server/src/main/java/com/mainproject/server/member/service/RankingScheduler.java
  server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
  server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
  server/server/src/main/resources/application.properties
Labels: back-end
