Repository codestates-seb/seb40_main_014, pull requests merged in 2022-11, with the labels that each got.

#3 ✨Feat: 로딩 컴포넌트 구현
  client/.eslintrc.json
  client/src/assets/images/spinner.json
  client/src/components/common/Loading.tsx
  client/src/pages/Main.tsx
Labels: front-end, feature

#4 🔨Chore: 불필요한 파일 삭제, index.html 정리 외 4
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.tsx
  client/src/assets/styles/GlobalStyle.js
  client/src/pages/Main.tsx
Labels: front-end, feature

#14 ✨Feat : ChatRoom entity구현
  server/server/src/main/java/com/mainproject/server/ChatRoom/entity/ChatMessage.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/entity/ChatRoom.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/repository/ChatRoomRepository.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/service/ChatService.java
Labels: back-end, feature

#15 :sparkles: feat : playlistEntity 1차 구현
  server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
Labels: back-end, feature

#19 response, exception, member 기본기능
  server/server/src/main/java/com/mainproject/server/config/auth/WebSecurityConfigurerAdapter.java
  server/server/src/main/java/com/mainproject/server/config/auth/dto/OAuthAttributes.java
  server/server/src/main/java/com/mainproject/server/config/auth/dto/SessionMember.java
  server/server/src/main/java/com/mainproject/server/exception/BusinessException.java
  server/server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
  server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
  server/server/src/main/java/com/mainproject/server/member/dto/MemberFollowDto.java
  server/server/src/main/java/com/mainproject/server/member/dto/MemberPatchDto.java
  server/server/src/main/java/com/mainproject/server/member/dto/MemberPostDto.java
  server/server/src/main/java/com/mainproject/server/member/dto/MemberResponseDto.java
  server/server/src/main/java/com/mainproject/server/member/entity/Follow.java
  server/server/src/main/java/com/mainproject/server/member/entity/Member.java
  server/server/src/main/java/com/mainproject/server/member/entity/Ranking.java
  server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
  server/server/src/main/java/com/mainproject/server/member/repository/MemberRepository.java
  server/server/src/main/java/com/mainproject/server/member/service/CustomOAuth2UserService.java
  server/server/src/main/java/com/mainproject/server/member/service/MemberService.java
  server/server/src/main/java/com/mainproject/server/response/MultiResponseDto.java
  server/server/src/main/java/com/mainproject/server/response/PageInfo.java
  server/server/src/main/java/com/mainproject/server/response/SingleResponseDto.java
Labels: back-end, feature

#23 ✨Feat: 플레이리스트 상세 화면 구현
  client/.eslintrc.json
  client/.gitignore
  client/data/data.json
  client/package-lock.json
  client/package.json
  client/src/api/listApi.ts
  client/src/api/root.ts
  client/src/assets/styles/GlobalStyle.ts
  client/src/components/common/BookMark.tsx
  client/src/components/common/Category.tsx
  client/src/components/common/Toggle.tsx
  client/src/components/playlist/MusicList.tsx
  client/src/components/playlist/PlayListInfo.tsx
  client/src/components/playlist/PlayListSetting.jsx
  client/src/pages/PlayListDetail.tsx
  client/src/pages/PlayListModify.tsx
  client/src/routes/AppRouter.tsx
  client/tsconfig.json
Labels: front-end, feature

#30 ✨feat : ChatController 1차 구현
  server/server/build.gradle
  server/server/src/main/java/com/mainproject/server/ChatRoom/config/ChatConfig.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/config/WebSocketConfig.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/config/WebSocketHandler.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/controller/ChatController.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/controller/RoomController.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/ChatRoomCountDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/ChatRoomDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/ChatRoomPatchDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/ChatRoomPostDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/ChatRoomResDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/entity/ChatMessage.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/entity/ChatRoom.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/mapper/ChatRoomMapper.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/repository/ChatRoomRepository.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/service/ChatService.java
  server/server/src/main/java/com/mainproject/server/config/auth/WebSecurityConfigurerAdapter.java
  server/server/src/main/java/com/mainproject/server/member/entity/Member.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
  server/server/src/main/resources/application-server.yml
  server/server/src/main/resources/application.yml
Labels: back-end, feature

#31 ✨Feat: 마이페이지 1차 구현 완료
  client/package-lock.json
  client/package.json
  client/src/components/Mypage/Content.tsx
  client/src/components/Mypage/MypageContents.tsx
  client/src/components/Mypage/MypageInfo.tsx
  client/src/components/common/BookMark.tsx
  client/src/components/common/Button.tsx
  client/src/components/common/Toggle.tsx
  client/src/components/playlist/MusicList.tsx
  client/src/components/playlist/PlayListInfo.tsx
  client/src/components/playlist/PlayListSetting.tsx
  client/src/components/playlistcollection/CplayList.tsx
  client/src/pages/Mypage.tsx
  client/src/pages/PlayListCollection.tsx
  client/src/pages/PlayListDetail.tsx
  client/src/pages/PlayListModify.tsx
  client/src/routes/AppRouter.tsx
Labels: front-end, feature

#37 :sparkles: feat : playlist dto/entity/repo/service
  server/server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPatchDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPostDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/SimplePlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/Category.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
  server/server/src/main/java/com/mainproject/server/playlist/repository/CategoryRepository.java
  server/server/src/main/java/com/mainproject/server/playlist/repository/PlaylistRepository.java
  server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java
Labels: back-end, feature

#33 ✨Feat: client 배포 자동화
  .github/workflows/front.yml
Labels: front-end, feature

#38 Feat : playlist crud 1차구현 완료 #1
  server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPatchDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/SimplePlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
  server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
  server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java
Labels: back-end, feature

#39 ✨Feat: 플레이리스트 CRUD 1차 구현
  client/data/data.json
  client/package-lock.json
  client/package.json
  client/src/api/listApi.ts
  client/src/api/root.ts
  client/src/api/youtubeApi.ts
  client/src/assets/images/arrowCursor.png
  client/src/components/Mypage/MypageContents.tsx
  client/src/components/common/Toggle.tsx
  client/src/components/playlist/MusicList.tsx
  client/src/components/playlist/PlayListInfo.tsx
  client/src/components/playlist/PlayListSetting.tsx
  client/src/components/playlistcollection/CplayList.tsx
  client/src/index.tsx
  client/src/pages/MakePlayList.tsx
  client/src/pages/PlayListDetail.tsx
  client/src/pages/PlayListModify.tsx
  client/src/pages/PlaylistList.tsx
  client/src/routes/AppRouter.tsx
Labels: front-end, feature

#42 ✨Feat: chatcontroller 수정 및 roomMember entity 추가 구현
  server/server/build.gradle
  server/server/src/main/java/com/mainproject/server/ChatRoom/config/WebSocketHandler.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/config/WebSocketTest.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/controller/ChatController.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/controller/RoomController.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/ChatRoomDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/ChatRoomPostDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/ChatRoomResDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/ResponseChatRoomDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/entity/ChatMessage.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/entity/ChatRoom.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/mapper/ChatRoomMapper.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/repository/ChatMessageRepository.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/repository/ChatRoomRepository.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/service/ChatService.java
  server/server/src/main/java/com/mainproject/server/auth/config/WebSecurityConfigurerAdapter.java
  server/server/src/main/java/com/mainproject/server/auth/handler/OAuth2SuccessHandler.java
  server/server/src/main/java/com/mainproject/server/auth/utils/CustomAuthorityUtil.java
  server/server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
  server/server/src/main/java/com/mainproject/server/member/dto/MemberResponseDto.java
  server/server/src/main/java/com/mainproject/server/member/entity/Member.java
  server/server/src/main/java/com/mainproject/server/member/entity/Ranking.java
  server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
  server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPatchDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPostDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/SimplePlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/Category.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/playlistDto.java
  server/server/src/main/java/com/mainproject/server/playlist/repository/PlaylistRepository.java
  server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java
  server/server/src/main/java/com/mainproject/server/roomMember/entity/roomMember.java
Labels: back-end, feature, chore

#44 ✅Test: 구글로그인/로그아웃/본인정보조회 테스트 완료
  client/data/data.json
  client/src/api/authApi.ts
  client/src/api/listApi.ts
  client/src/api/root.ts
  client/src/api/userApi.ts
  client/src/assets/images/profile.jpg
  client/src/assets/images/spinner2.json
  client/src/components/common/Loading.tsx
  client/src/components/home/Header.tsx
  client/src/components/home/LoginModal.tsx
  client/src/components/home/MobileUl.tsx
  client/src/components/home/Playlist.tsx
  client/src/components/home/Room.tsx
  client/src/pages/PlaylistList.tsx
  client/src/pages/RoomList.tsx
  client/src/slices/mySlice.ts
  client/src/store/store.ts
Labels: front-end, feature

#46 🐛 fix : token 수정
  server/server/src/main/java/com/mainproject/server/auth/config/WebConfig.java
  server/server/src/main/java/com/mainproject/server/auth/filter/JwtVerificationFilter.java
  server/server/src/main/java/com/mainproject/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/server/src/main/java/com/mainproject/server/auth/handler/OAuth2SuccessHandler.java
  server/server/src/main/java/com/mainproject/server/auth/utils/ErrorResponder.java
  server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
  server/server/src/main/java/com/mainproject/server/member/jwt/JwtTokenizer.java
  server/server/src/main/java/com/mainproject/server/member/service/MemberService.java
  server/server/src/main/java/com/mainproject/server/response/ErrorResponse.java
Labels: enhancement, back-end

#52 ✨Feat: 플리 좋아요,북마크 구현
  client/data/data.json
  client/src/api/playlistApi.ts
  client/src/api/roomApi.ts
  client/src/components/common/BookMark.tsx
  client/src/components/common/Like.tsx
  client/src/components/home/Playlist.tsx
  client/src/components/playlist/MusicList.tsx
  client/src/components/playlist/PlayListInfo.tsx
  client/src/components/playlist/PlayListSetting.tsx
  client/src/components/playlistcollection/CplayList.tsx
  client/src/pages/MakePlayList.tsx
  client/src/pages/PlayListCollection.tsx
  client/src/pages/PlayListDetail.tsx
  client/src/pages/PlaylistList.tsx
  client/src/routes/AppRouter.tsx
  client/src/slices/mySlice.ts
Labels: front-end, feature

#74 :hammer: chore : authorization추가, 짜잘한 수정
  server/server/src/main/java/com/mainproject/server/ServerApplication.java
  server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPostDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
  server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java
Labels: back-end, chore

#75 ✨ feat : follow 구현
  server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
  server/server/src/main/java/com/mainproject/server/member/dto/MemberResponseDto.java
  server/server/src/main/java/com/mainproject/server/member/entity/Follow.java
  server/server/src/main/java/com/mainproject/server/member/entity/Member.java
  server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
  server/server/src/main/java/com/mainproject/server/member/repository/FollowRepository.java
  server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
  server/server/src/main/java/com/mainproject/server/member/service/MemberService.java
  server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
  server/server/src/main/resources/static/index.html
Labels: back-end, feature

#83 ✅Test: 회원정보수정 테스트 완료 외 3
  client/public/index.html
  client/src/api/userApi.ts
  client/src/assets/images/playlist-thumbnail.png
  client/src/assets/images/profile.jpg
  client/src/assets/images/spinner2.json
  client/src/components/Mypage/EditProfileModal.tsx
  client/src/components/Mypage/MypageContents.tsx
  client/src/components/Mypage/MypageInfo.tsx
  client/src/components/chat/ChatStompTest.tsx
  client/src/components/chat/ChatStompTest2.tsx
  client/src/components/common/Badge.tsx
  client/src/components/common/Category.tsx
  client/src/components/common/Layout.tsx
  client/src/components/common/ScrollToTop.tsx
  client/src/components/home/Footer.tsx
  client/src/components/home/Header.tsx
  client/src/components/home/LoginModal.tsx
  client/src/components/home/MobileUl.tsx
  client/src/components/home/PcUl.tsx
  client/src/components/home/Playlist.tsx
  client/src/components/home/Room.tsx
  client/src/components/playlist/MusicList.tsx
  client/src/components/playlist/PlayListSetting.tsx
  client/src/components/room/Chatting.tsx
  client/src/pages/EditProfile.tsx
  client/src/pages/LoginCallback.tsx
  client/src/pages/PlayListCollection.tsx
  client/src/pages/PlaylistList.tsx
  client/src/pages/RoomList.tsx
Labels: front-end, feature

#87 Playlist/upgrade
  server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistItemDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistItemResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPatchDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPostDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/SimplePlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/CategoryDetail.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/PlaylistItem.java
  server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
  server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java
Labels: back-end

#89 ✨ feat : ranking
  server/server/src/main/java/com/mainproject/server/auth/config/SecurityConfig.java
  server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
  server/server/src/main/java/com/mainproject/server/member/dto/RankResponseDto.java
  server/server/src/main/java/com/mainproject/server/member/entity/Member.java
  server/server/src/main/java/com/mainproject/server/member/entity/Ranking.java
  server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
  server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
  server/server/src/main/java/com/mainproject/server/redis/config/RedisConfig.java
Labels: back-end, feature

#91 ✨ Feat: 플리 생성 조회 완료
  client/src/api/playlistApi.ts
  client/src/api/root.ts
  client/src/api/youtubeApi.ts
  client/src/components/Mypage/Content.tsx
  client/src/components/Mypage/MypageContents.tsx
  client/src/components/common/BookMark.tsx
  client/src/components/common/Like.tsx
  client/src/components/home/Playlist.tsx
  client/src/components/playlist/MusicList.tsx
  client/src/components/playlist/PlayListInfo.tsx
  client/src/components/playlist/PlayListSetting.tsx
  client/src/components/playlistcollection/CplayList.tsx
  client/src/pages/MakePlayList.tsx
  client/src/pages/Mypage.tsx
  client/src/pages/PlayListCollection.tsx
  client/src/pages/PlayListDetail.tsx
  client/src/pages/PlaylistList.tsx
  client/src/slices/mySlice.ts
Labels: front-end, feature

#104 ✨ Feat: 플레이 리스트 테스트 완료
  client/data/mypage.json
  client/src/api/playlistApi.ts
  client/src/api/userApi.ts
  client/src/components/Mypage/Content.tsx
  client/src/components/Mypage/MypageContents.tsx
  client/src/components/common/BookMark.tsx
  client/src/components/common/Like.tsx
  client/src/components/home/Header.tsx
  client/src/components/home/Playlist.tsx
  client/src/components/playlist/PlayListInfo.tsx
  client/src/components/playlistcollection/CplayList.tsx
  client/src/components/playlistcollection/ModifyButton.tsx
  client/src/pages/MakePlayList.tsx
  client/src/pages/Mypage.tsx
  client/src/pages/PlayListCollection.tsx
  client/src/pages/PlayListDetail.tsx
  client/src/pages/PlaylistList.tsx
  client/src/pages/RoomList.tsx
  client/src/routes/AppRouter.tsx
Labels: front-end, feature

#105 🔨 chore : CategoryList 변수명 수정
  server/server/src/main/java/com/mainproject/server/playlist/dto/LikePlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPatchDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPostDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/SimplePlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
  server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
  server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java
Labels: back-end, chore

#109 🔨 chore : chatroom 조회시 방안의 playlist만 응답값에 반영
  server/server/src/main/java/com/mainproject/server/ChatRoom/controller/ChatController.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/controller/RoomController.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/MemRoomResponseDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/MemberChatRoomDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/ResponseChatRoomDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/SimpleMemChatResponseDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/entity/ChatRoomDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/mapper/ChatRoomMapper.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/repository/ChatMessageRepository.java
Labels: back-end, chore

#110 🐛 Fix: playlist delete navigate
  client/src/components/playlistcollection/CplayList.tsx
  client/src/components/playlistcollection/ModifyButton.tsx
  client/src/pages/PlayListCollection.tsx
Labels: bug, front-end

#120 ✨ feat : PlSearch
  server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
  server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
  server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
  server/server/src/main/java/com/mainproject/server/playlist/repository/PlaylistRepository.java
  server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java
Labels: back-end, feature

#122 🔨 chore : 조회순 인기 방장순 정렬 api, 중복 memberName ExceptionCode 반환
  server/server/src/main/java/com/mainproject/server/ChatRoom/controller/ChatController.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/controller/RoomController.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/mapper/ChatRoomMapper.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/repository/ChatRoomRepository.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/service/ChatService.java
  server/server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
Labels: back-end, chore

#125 🔨 chore : search 페이지네이션 추가
  server/server/src/main/java/com/mainproject/server/ChatRoom/controller/RoomController.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/service/ChatService.java
  server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
  server/server/src/main/java/com/mainproject/server/member/service/MemberService.java
  server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
  server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
  server/server/src/main/java/com/mainproject/server/playlist/repository/PlaylistRepository.java
  server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java
Labels: back-end, chore

#130 Feat: 현재 진행중인 곡 표시, 이미지 화질 수정
  client/src/assets/images/play.json
  client/src/components/playlist/PlayListSetting.tsx
  client/src/components/room/Playlist.tsx
Labels: front-end, feature

#137 ✨ feat : Grade / 중복닉네임검사, 자기소개 추가
  server/server/src/main/java/com/mainproject/server/advice/GlobalExceptionAdvice.java
  server/server/src/main/java/com/mainproject/server/exception/ExceptionCode.java
  server/server/src/main/java/com/mainproject/server/member/controller/MemberController.java
  server/server/src/main/java/com/mainproject/server/member/dto/MemberPatchDto.java
  server/server/src/main/java/com/mainproject/server/member/dto/MemberResponseDto.java
  server/server/src/main/java/com/mainproject/server/member/dto/RankResponseDto.java
  server/server/src/main/java/com/mainproject/server/member/dto/SimpleMemberResponseDto.java
  server/server/src/main/java/com/mainproject/server/member/entity/Member.java
  server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
  server/server/src/main/java/com/mainproject/server/member/repository/MemberRepository.java
  server/server/src/main/java/com/mainproject/server/member/service/FollowService.java
  server/server/src/main/java/com/mainproject/server/member/service/MemberService.java
  server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/LikePlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
Labels: back-end, feature

#140 :sparkles: feat : 좋아요순 정렬 기능 구현
  server/server/src/main/java/com/mainproject/server/playlist/controller/PlaylistController.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/PlaylistPostDto.java
  server/server/src/main/java/com/mainproject/server/playlist/dto/SimplePlaylistResponseDto.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/CategoryDetail.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/Likes.java
  server/server/src/main/java/com/mainproject/server/playlist/entity/Playlist.java
  server/server/src/main/java/com/mainproject/server/playlist/mapper/PlaylistMapper.java
  server/server/src/main/java/com/mainproject/server/playlist/service/PlaylistService.java
Labels: back-end, feature

#142 🐛 fix : chatroom rank 정렬 v3
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/RankResponseChatRoomDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/mapper/ChatRoomMapper.java
  server/server/src/main/java/com/mainproject/server/advice/GlobalExceptionAdvice.java
Labels: back-end, chore

#139 🐛 Fix: 피드백 수정
  client/src/components/common/BookMark.tsx
  client/src/components/playlist/MusicList.tsx
  client/src/components/playlist/PlayListInfo.tsx
  client/src/components/playlist/PlayListSetting.tsx
  client/src/components/playlistcollection/CplayList.tsx
  client/src/components/room/Playlist.tsx
Labels: bug, front-end

#147 🐛 fix : chatroom rank 정렬 v4
  server/server/src/main/java/com/mainproject/server/ChatRoom/controller/ChatController.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/controller/RoomController.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/dto/RankResponseChatRoomDto.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/entity/ChatRoom.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/mapper/ChatRoomMapper.java
  server/server/src/main/java/com/mainproject/server/ChatRoom/repository/ChatRoomRepository.java
  server/server/src/main/java/com/mainproject/server/member/dto/RankChatRoomSimpleDto.java
  server/server/src/main/java/com/mainproject/server/member/mapper/MemberMapper.java
Labels: back-end, chore
